baseURL: https://pietro-rocco-di-torrepadula-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Pietro Rocco di Torrepadula
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Data Analytics - individual project
    title: Hi, my name is Pietro, I'm a student at LBS and this is my portfolio website
  blog: {}
  contact:
    address:
      - city: London, W2 5DH
        country: UK
        street: 37, Moorhouse Rd
        title: Home
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: pietror.mfa2022@london.edu
        title: School e-mail
    enable: yes
    phone:
      - phone: please request phone contact by e-mail
        title: Phone contact
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    #copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#    - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/pietro.roccoditorrepadula
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/pietro__crt/?hl=it
      - icon: fa-github
        label: GitHub
        url: https://github.com/PietroCRT
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/pietro-rocco-di-torrepadula-397b51187/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: My Articles
        url: blogs
      - name: My CV
        url: cv/my_cv
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pietro.jpeg
        subtitle: A glimpse of who I am and of my experiences
        title: My Curriculum Vitae
        url: cv/my_cv
      - image: face2face.jpg
        subtitle: Analysis of the impact of political preferences on global warming beliefs
        title: Global Warming and Political View in the U.S
        url: blogs/global_warming
      - image: chair.jpeg
        subtitle: Do the ratings for different directos have statistically significant differences in their averages?
        title: The Effect of Directors on Movie Ratings
        url: blogs/movies_imdb
      - image: infl.png
        subtitle: How did CPI and its components change in the last few years?
        title: Change in CPI and Its Components
        url: blogs/cpi_change
      - image: boris.jpg
        subtitle: How have the monthly rentals moved around their long-term monthly mean in the last years?
        title: Fluctuations in Monthly TFL Bike Rentals
        url: blogs/tfl_bike
      - image: gdp.jpg
        subtitle: How the proportional importance of components of GDP evolved over time in different countries
        title: Evolution of GDP Components Across Countries
        url: blogs/gdp_components
  two:
    buttonText: Back to My work
    enable: yes
    subtitle: "Plese consider following me on social media and don't hesitate to contact me by e-mail."
    title: Thanks for checking out work!
    url: blogs
    
    
         
